services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: qlora-backend
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - TRANSFORMERS_OFFLINE=${TRANSFORMERS_OFFLINE:-1}
    command:
      - uvicorn
      - backend.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8000}
    container_name: qlora-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  trainer:
    build:
      context: .
      dockerfile: docker/trainer.Dockerfile
    container_name: qlora-trainer
    working_dir: /workspace
    volumes:
      - ./:/workspace
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    command:
      - bash
      - scripts/run_training.sh
